"""P2-M09 frozen H1 legacy residual evaluation; one sequential run only."""
from __future__ import annotations
import csv, gzip, hashlib, io, json, math, os, platform, resource, sys, time
from collections import defaultdict
from datetime import datetime, timezone
from pathlib import Path
import lightgbm, numpy as np, scipy
from src.market.calibration import fit_power_gamma
from src.models.backends.lightgbm.backend import raw_residual_prediction, train_inner_with_zero_tree_early_stopping, train_outer_fixed_iterations
from src.models.backends.lightgbm.dataset import group_sizes, sorted_training_rows
from src.models.market_offset.loss import mean_race_log_loss
from src.models.market_offset.prediction import predict_win_market_offset
from src.models.market_offset.preprocessing import FoldSafePreprocessor

ROOT=Path(__file__).resolve().parents[2]; FRAME=ROOT/'data/curated/p2_model/win/historical_reference/fs00_legacy_market_offset_training_frame_v1.csv.gz'; M08=ROOT/'data/manifests/P2_WIN_RESIDUAL_BACKEND_V1_MANIFEST.json'; BACK=ROOT/'configs/models/P2_WIN_RESIDUAL_BACKEND_V1.yaml'; GRID=ROOT/'configs/models/P2_WIN_H1_LEGACY_RESIDUAL_GRID_V1.yaml'; WF=ROOT/'configs/evaluation/P2_WIN_HISTORICAL_WALKFORWARD_V1.yaml'; SEL=ROOT/'configs/evaluation/P2_WIN_H1_SELECTION_RULE_V1.yaml'; RECOVERY=ROOT/'configs/evaluation/P2_M09_INCIDENT_RECOVERY_V1.yaml'; RECOVERY_RUN=ROOT/'audit/data/p2_m09r/run_manifest.json'; FEATURES=ROOT/'configs/features/P2_V1_LEGACY_FEATURE_LIST_V1.yaml'; BUDGET=ROOT/'audit/data/p2_m08b/search_budget_registration.csv'; OUT=ROOT/'data/curated/p2_model/win/h1'; AUD=ROOT/'audit/data/p2_m09'; CP=AUD/'checkpoints'; MODELS=ROOT/'models/development/p2_m09'; MAN=ROOT/'data/manifests'; SELECTED=ROOT/'configs/models/P2_WIN_H1_SELECTED_HISTORICAL_V1.yaml'; REPORT=ROOT/'reports/development/P2_M09_H1_LEGACY_RESIDUAL_DEVELOPMENT_REPORT.md'
INCIDENT_ID='P2-INC-001'; FORMAL_EVIDENCE_STATUS='DEVELOPMENT_EVALUATION_WITH_RECORDED_PROTOCOL_INCIDENT'
RUNNER=('race_key','race_date','venue','horse_number','config_id','fold_id','q_raw','gamma_outer','market_calibrated_p','residual_score_raw','candidate_probability','edge_log_ratio','win_soft_target','best_iteration','market_evidence_class','evidence_status','protocol_incident_recorded','incident_id','incidental_performance_peeks','outer_validation_contaminated','t15_equivalence','probability_edge_confirmed'); RACE=('race_key','race_date','venue','config_id','fold_id','market_loss_r','candidate_loss_r','delta_loss_r','raw_market_loss_r','best_iteration','market_evidence_class','evidence_status','protocol_incident_recorded','incident_id','incidental_performance_peeks','outer_validation_contaminated','t15_equivalence','probability_edge_confirmed'); FOLD=('config_id','fold_id','inner_train_races','inner_valid_races','outer_train_races','outer_valid_races','gamma_inner','gamma_outer','best_iteration','best_iteration_zero_flag','inner_market_ll','inner_candidate_ll','outer_market_ll','outer_candidate_ll','outer_delta_ll','market_evidence_class','evidence_status','protocol_incident_recorded','incident_id','incidental_performance_peeks','outer_validation_contaminated')
def sha(p):
 h=hashlib.sha256()
 with p.open('rb') as f:
  for b in iter(lambda:f.read(1048576),b''):h.update(b)
 return h.hexdigest()
def fmt(v): return '' if v is None else (format(v,'.17g') if isinstance(v,float) else str(v))
def logical(rows,fields):
 h=hashlib.sha256()
 for r in rows:h.update(json.dumps([fmt(r.get(f)) for f in fields],ensure_ascii=False,separators=(',',':')).encode()+b'\n')
 return h.hexdigest()
def atomic(p,t):
 p.parent.mkdir(parents=True,exist_ok=True);q=p.parent/('.'+p.name+'.work');q.write_text(t,encoding='utf8');os.replace(q,p)
def csvout(p,rows,fields=None):
 fields=list(fields or dict.fromkeys(k for r in rows for k in r) or ['status']);p.parent.mkdir(parents=True,exist_ok=True)
 with p.open('w',encoding='utf8',newline='') as f:
  w=csv.DictWriter(f,fieldnames=fields);w.writeheader();w.writerows({x:fmt(r.get(x)) for x in fields} for r in rows)
def gzout(p,rows,fields):
 p.parent.mkdir(parents=True,exist_ok=True);q=p.parent/('.'+p.name+'.work')
 with q.open('wb') as raw:
  with gzip.GzipFile(filename='',mode='wb',fileobj=raw,mtime=0) as z:
   with io.TextIOWrapper(z,encoding='utf8',newline='') as f:
    w=csv.DictWriter(f,fieldnames=fields);w.writeheader();w.writerows({x:fmt(r.get(x)) for x in fields} for r in rows)
 os.replace(q,p)
def readgz(p):
 with gzip.open(p,'rt',encoding='utf8',newline='') as f:return list(csv.DictReader(f))
def jread(p):return json.loads(p.read_text(encoding='utf8'))
def races(rows):
 d=defaultdict(list)
 for r in sorted_training_rows(rows):d[r['race_key']].append(r)
 return list(d.values())
def subset(rows,a,b):
 x=sorted_training_rows([r for r in rows if a<=r['race_date']<=b])
 if not x:raise RuntimeError('empty frozen fold')
 return x
def gamma(rows):
 z=fit_power_gamma([[{'horse_number':x['horse_number'],'log_q_raw':x['log_q_raw'],'win_soft_target':x['win_soft_target']} for x in rr] for rr in races(rows)])
 if z['status']!='GAMMA_SOLVED':raise RuntimeError('gamma solve failed')
 return z['gamma']
def cmap(p):return hashlib.sha256(json.dumps(p.category_maps,ensure_ascii=False,sort_keys=True,separators=(',',':')).encode()).hexdigest()
def params(common,c):return {**common,**{k:v for k,v in c.items() if k!='config_id'},'boosting':'gbdt','verbosity':-1,'feature_pre_filter':False}
def execute(frame,specs,fold,config,gi,go,persist):
 it=subset(frame,fold['inner_train_start'],fold['inner_train_end']);iv=subset(frame,fold['inner_valid_start'],fold['inner_valid_end']);ot=subset(frame,fold['outer_train_start'],fold['outer_train_end']);ov=subset(frame,fold['outer_valid_start'],fold['outer_valid_end']);pa=params(GRID_JSON['common'],config);pi=FoldSafePreprocessor(specs).fit(it)
 inner=train_inner_with_zero_tree_early_stopping(lightgbm,it,iv,pi.transform(it),pi.transform(iv),pi.categorical_indices,gi,pa);best=inner['best_iteration'];po=FoldSafePreprocessor(specs).fit(ot);model=train_outer_fixed_iterations(lightgbm,ot,po.transform(ot),po.categorical_indices,go,pa,best);res=np.zeros(len(ov)) if model is None else raw_residual_prediction(model,po.transform(ov));pred=predict_win_market_offset(ov,res.tolist(),go);pm={(r['race_key'],r['horse_number']):r for r in pred};rr=[];by=defaultdict(list)
 for x in ov:
  p=pm[(x['race_key'],x['horse_number'])];r={'race_key':x['race_key'],'race_date':x['race_date'],'venue':x['venue'],'horse_number':x['horse_number'],'config_id':config['config_id'],'fold_id':fold['fold_id'],'q_raw':p['q_raw'],'gamma_outer':go,'market_calibrated_p':p['market_calibrated_p'],'residual_score_raw':p['residual_score_raw'],'candidate_probability':p['candidate_probability'],'edge_log_ratio':p['edge_log_ratio'],'win_soft_target':x['win_soft_target'],'best_iteration':best,'market_evidence_class':'HISTORICAL_MARKET_TIME_UNKNOWN','evidence_status':FORMAL_EVIDENCE_STATUS,'protocol_incident_recorded':True,'incident_id':INCIDENT_ID,'incidental_performance_peeks':1,'outer_validation_contaminated':False,'t15_equivalence':False,'probability_edge_confirmed':False};rr.append(r);by[x['race_key']].append(r)
 mr=[]
 for k,rs in sorted(by.items()):
  rs=sorted(rs,key=lambda x:int(x['horse_number']));y=[float(x['win_soft_target']) for x in rs];m=[float(x['market_calibrated_p']) for x in rs];c=[float(x['candidate_probability']) for x in rs];q=[float(x['q_raw']) for x in rs]
  if min(m+c)<=0 or abs(sum(m)-1)>1e-12 or abs(sum(c)-1)>1e-12:raise RuntimeError('invalid race probability')
  ml=mean_race_log_loss(m,y,[len(rs)]);cl=mean_race_log_loss(c,y,[len(rs)]);mr.append({'race_key':k,'race_date':rs[0]['race_date'],'venue':rs[0]['venue'],'config_id':config['config_id'],'fold_id':fold['fold_id'],'market_loss_r':ml,'candidate_loss_r':cl,'delta_loss_r':cl-ml,'raw_market_loss_r':mean_race_log_loss(q,y,[len(rs)]),'best_iteration':best,'market_evidence_class':'HISTORICAL_MARKET_TIME_UNKNOWN','evidence_status':FORMAL_EVIDENCE_STATUS,'protocol_incident_recorded':True,'incident_id':INCIDENT_ID,'incidental_performance_peeks':1,'outer_validation_contaminated':False,'t15_equivalence':False,'probability_edge_confirmed':False})
 if best==0 and (max(abs(float(x['candidate_probability'])-float(x['market_calibrated_p'])) for x in rr)>1e-12 or max(abs(float(x['delta_loss_r'])) for x in mr)>1e-12):raise RuntimeError('zero tree identity failure')
 mp=zp='';mh=''
 if persist:
  base=MODELS/config['config_id']/fold['fold_id'];base.mkdir(parents=True,exist_ok=True)
  if best:
   f=base/'model.txt';model.save_model(str(f));mp=str(f.relative_to(ROOT));mh=sha(f)
  else:
   f=base/'ZERO_TREE_MARKET_BASELINE.json';atomic(f,json.dumps({'status':'ZERO_TREE_MARKET_BASELINE','best_iteration':0,'gamma_outer':go,'candidate_equals_calibrated_market':True},indent=2)+'\n');zp=str(f.relative_to(ROOT));mh=sha(f)
 s={'config_id':config['config_id'],'fold_id':fold['fold_id'],'inner_train_races':len(races(it)),'inner_valid_races':len(races(iv)),'outer_train_races':len(races(ot)),'outer_valid_races':len(races(ov)),'gamma_inner':gi,'gamma_outer':go,'best_iteration':best,'best_iteration_zero_flag':best==0,'inner_market_ll':inner['iteration0_market_ll'],'inner_candidate_ll':inner['best_inner_ll'],'outer_market_ll':float(np.mean([x['market_loss_r'] for x in mr])),'outer_candidate_ll':float(np.mean([x['candidate_loss_r'] for x in mr])),'outer_delta_ll':float(np.mean([x['delta_loss_r'] for x in mr])),'market_evidence_class':'HISTORICAL_MARKET_TIME_UNKNOWN','evidence_status':FORMAL_EVIDENCE_STATUS,'protocol_incident_recorded':True,'incident_id':INCIDENT_ID,'incidental_performance_peeks':1,'outer_validation_contaminated':False,'category_map_inner_hash':cmap(pi),'category_map_outer_hash':cmap(po),'model_path':mp,'zero_tree_path':zp,'model_file_hash':mh,'prediction_logical_hash':logical(rr,RUNNER),'inner_history':inner['history']}
 return s,rr,mr

def main():
 global GRID_JSON
 started=time.monotonic()
 if os.environ.get('P2_FORMAL_M09_EVALUATION')!='1':raise RuntimeError('P2_FORMAL_M09_EVALUATION=1 is required for any real-data M09 performance evaluation')
 if (AUD/'run_manifest.json').exists() or SELECTED.exists():raise RuntimeError('formal M09 artifacts exist; do not silently rerun performance evaluation')
 recovery=jread(RECOVERY);recovery_run=jread(RECOVERY_RUN)
 required_recovery={'incident_id':INCIDENT_ID,'incident_scope':'INNER_VALIDATION_ONLY','incidental_peek_count':1,'formal_search_budget_consumed':0,'formal_search_budget_remaining':6,'outer_validation_contaminated':False,'adaptive_model_change_detected':False,'new_unseen_development_data_required':False,'resume_original_m09':True,'resume_requires_no_protocol_change':True,'evidence_label_after_resume':FORMAL_EVIDENCE_STATUS,'formal_execution_guard':'P2_FORMAL_M09_EVALUATION=1'}
 if any(recovery.get(k)!=v for k,v in required_recovery.items()) or recovery_run.get('status')!='AUTHORIZED_TO_RESUME_P2_M09_UNCHANGED':raise RuntimeError('BLOCKED_IN_P2_M09_RECOVERY_STATE')
 frame=readgz(FRAME);m08=jread(M08);back=jread(BACK);GRID_JSON=jread(GRID);walk=jread(WF);sel=jread(SEL);features=jread(FEATURES);specs=features['features'];fcols=tuple(frame[0])
 if len(frame)!=9522 or len({r['race_key'] for r in frame})!=833 or len(specs)!=119 or logical(frame,fcols)!=m08['training_frame_logical_hash']:raise RuntimeError('frozen FS00 frame mismatch')
 b=list(csv.DictReader(BUDGET.open(encoding='utf8')))
 if len(b)!=1 or b[0]['registered']!='6' or b[0]['consumed_performance_evaluations']!='0' or b[0]['remaining_after_m08b']!='6' or len(GRID_JSON['configs'])!=6:raise RuntimeError('search budget inconsistent before performance')
 if {c['config_id'] for c in GRID_JSON['configs']}!={'H1-C01','H1-C02','H1-C03','H1-C04','H1-C05','H1-C06'} or {f['fold_id'] for f in walk['folds']}!={'WF1','WF2','WF3'}:raise RuntimeError('unregistered M09 config or fold')
 if back['backend']!='lightgbm' or back['backend_version']!=lightgbm.__version__ or back['market_offset_implementation']!='NATIVE_INIT_SCORE_V1':raise RuntimeError('backend environment mismatch')
 folds=walk['folds'];g={};counts=[]
 for f in folds:
  it=subset(frame,f['inner_train_start'],f['inner_train_end']);iv=subset(frame,f['inner_valid_start'],f['inner_valid_end']);ot=subset(frame,f['outer_train_start'],f['outer_train_end']);ov=subset(frame,f['outer_valid_start'],f['outer_valid_end']);g[f['fold_id']]={'inner':gamma(it),'outer':gamma(ot)};counts.append({'fold_id':f['fold_id'],'inner_train_races':len(races(it)),'inner_valid_races':len(races(iv)),'outer_train_races':len(races(ot)),'outer_valid_races':len(races(ov)),'inner_train_runners':len(it),'inner_valid_runners':len(iv),'outer_train_runners':len(ot),'outer_valid_runners':len(ov)})
 CP.mkdir(parents=True,exist_ok=True);summ=[];runner=[];rmetrics=[];models=[];det=None
 for c in GRID_JSON['configs']:
  for f in folds:
   cp=CP/(c['config_id']+'__'+f['fold_id']+'.complete.json')
   if cp.exists():raise RuntimeError('completed formal checkpoint exists; never rerun it')
   s,rr,mr=execute(frame,specs,f,c,g[f['fold_id']]['inner'],g[f['fold_id']]['outer'],True);summ.append(s);runner.extend(rr);rmetrics.extend(mr)
   atomic(cp,json.dumps({'status':'COMPLETE','config_id':c['config_id'],'fold_id':f['fold_id'],'summary':{k:v for k,v in s.items() if k!='inner_history'},'completed_at':datetime.now(timezone.utc).isoformat()},ensure_ascii=False,indent=2,sort_keys=True)+'\n');models.append({'config_id':c['config_id'],'fold_id':f['fold_id'],'best_iteration':s['best_iteration'],'model_path':s['model_path'],'zero_tree_path':s['zero_tree_path'],'model_file_hash':s['model_file_hash'],'category_map_inner_hash':s['category_map_inner_hash'],'category_map_outer_hash':s['category_map_outer_hash'],'prediction_logical_hash':s['prediction_logical_hash']})
   if c['config_id']=='H1-C01' and f['fold_id']=='WF1':
    r2,rr2,mr2=execute(frame,specs,f,c,g[f['fold_id']]['inner'],g[f['fold_id']]['outer'],False);det={'config_id':'H1-C01','fold_id':'WF1','first_prediction_hash':s['prediction_logical_hash'],'second_prediction_hash':r2['prediction_logical_hash'],'identical':s['prediction_logical_hash']==r2['prediction_logical_hash'],'selection_rows_counted_once':True}
    if not det['identical']:raise RuntimeError('real fold determinism failed')
 if len(summ)!=18:raise RuntimeError('config-fold coverage failure')
 ag=[]
 for c in GRID_JSON['configs']:
  x=[r for r in rmetrics if r['config_id']==c['config_id']];ag.append({'config_id':c['config_id'],'max_depth':c['max_depth'],'num_leaves':c['num_leaves'],'lambda_l2':c['lambda_l2'],'outer_validation_races':len(x),'pooled_candidate_ll':float(np.mean([r['candidate_loss_r'] for r in x])),'pooled_market_ll':float(np.mean([r['market_loss_r'] for r in x])),'pooled_delta_mean':float(np.mean([r['delta_loss_r'] for r in x]))})
 low=min(x['pooled_delta_mean'] for x in ag);tied=[x for x in ag if x['pooled_delta_mean']<=low+float(GRID_JSON['tie_tolerance'])];chosen=sorted(tied,key=lambda x:(-x['lambda_l2'],x['max_depth'],x['config_id']))[0];sid=chosen['config_id'];sr=[x for x in rmetrics if x['config_id']==sid];sp=[x for x in runner if x['config_id']==sid]
 by=defaultdict(list)
 for x in sr:by[x['race_date']].append(x['delta_loss_r'])
 dates=sorted(by);rng=np.random.default_rng(20260818);boot=[]
 for i in range(10000):boot.append(float(np.mean([v for d in rng.integers(0,len(dates),len(dates)) for v in by[dates[int(d)]]])))
 bs={'replicates':10000,'seed':20260818,'point_mean':float(np.mean([x['delta_loss_r'] for x in sr])),'bootstrap_mean':float(np.mean(boot)),'two_sided_95_lower':float(np.percentile(boot,2.5)),'two_sided_95_upper':float(np.percentile(boot,97.5)),'one_sided_95_upper':float(np.percentile(boot,95)),'p_bootstrap_delta_ge_0':float(np.mean(np.asarray(boot)>=0)),'status':'H1_DEV_BOOTSTRAP_UPPER_LT_ZERO' if float(np.percentile(boot,95))<0 else 'H1_DEV_BOOTSTRAP_NOT_CLEAR','evidence_status':'DEVELOPMENT_DIAGNOSTIC_ONLY'}
 month=[];venue=[]
 for m in ('2026-05','2026-06','2026-07'):
  x=[r for r in sr if r['race_date'].startswith(m)];month.append({'month':m,'race_count':len(x),'candidate_ll':float(np.mean([r['candidate_loss_r'] for r in x])),'market_ll':float(np.mean([r['market_loss_r'] for r in x])),'delta_ll':float(np.mean([r['delta_loss_r'] for r in x]))})
 for v in ('大井','船橋','川崎','浦和'):
  x=[r for r in sr if r['venue']==v];venue.append({'venue':v,'race_count':len(x),'candidate_ll':float(np.mean([r['candidate_loss_r'] for r in x])),'market_ll':float(np.mean([r['market_loss_r'] for r in x])),'delta_ll':float(np.mean([r['delta_loss_r'] for r in x]))})
 d=np.asarray([r['delta_loss_r'] for r in sr]);rs=np.asarray([r['residual_score_raw'] for r in sp]);status='H1_HISTORICAL_DEVELOPMENT_SIGNAL' if chosen['pooled_delta_mean']<0 else 'H1_HISTORICAL_NO_SIGNAL'
 OUT.mkdir(parents=True,exist_ok=True);csvout(OUT/'h1_config_outer_fold_results_v1.csv',[{k:x[k] for k in FOLD} for x in summ],FOLD);gzout(OUT/'outer_validation_race_metrics_v1.csv.gz',rmetrics,RACE);gzout(OUT/'outer_validation_runner_predictions_v1.csv.gz',runner,RUNNER);gzout(OUT/'selected_h1_race_metrics_v1.csv.gz',sr,RACE)
 selected={'hypothesis':'H1_LEGACY_RESIDUAL','selected_config_id':sid,'backend':'LIGHTGBM_GBDT','feature_set':'FS00_LEGACY','market_evidence_class':'HISTORICAL_MARKET_TIME_UNKNOWN','evidence_status':FORMAL_EVIDENCE_STATUS,'protocol_incident_recorded':True,'incident_id':INCIDENT_ID,'incidental_performance_peek_count':1,'outer_validation_contaminated':False,'selection_data':'HISTORICAL_MARKET_TIME_UNKNOWN','selection_period':'2026-05 through 2026-07 outer validations','selection_metric':'POOLED_RACE_EQUAL_WEIGHT_DELTA_LL','selected_pooled_delta_ll':chosen['pooled_delta_mean'],'selected_pooled_candidate_ll':chosen['pooled_candidate_ll'],'selected_pooled_market_ll':chosen['pooled_market_ll'],'formal_search_budget':'6/6','model_use_status':'HISTORICAL_DEVELOPMENT_CONFIGURATION_ONLY','primary_live_model':False,'primary_gamma':'NOT_FROZEN','T15':'NOT_FROZEN','development_signal_status':status};atomic(SELECTED,json.dumps(selected,ensure_ascii=False,indent=2,sort_keys=True)+'\n')
 csvout(AUD/'pre_performance_search_budget_state.csv',[{'formal_configured':6,'formal_performance_consumed':0,'formal_remaining':6,'incidental_performance_peeks':1,'incident_id':INCIDENT_ID,'status':'PASS'}]);csvout(AUD/'protocol_incident_reference.csv',[{'protocol_incident_recorded':True,'incident_id':INCIDENT_ID,'incidental_performance_peeks':1,'outer_validation_contaminated':False,'evidence_status':FORMAL_EVIDENCE_STATUS,'incident_artifact':'audit/data/p2_m09/PRE_PERFORMANCE_PROTOCOL_INCIDENT.md'}]);csvout(AUD/'incident_exclusion_from_selection_audit.csv',[{'incident_id':INCIDENT_ID,'inner_probe_used_in_early_stopping':False,'used_in_config_selection':False,'used_in_pooled_metrics':False,'used_in_bootstrap':False,'used_in_model_artifact_selection':False,'used_in_formal_budget_result':False,'status':'EXCLUDED_FROM_FORMAL_SELECTION'}]);csvout(AUD/'zero_tree_clarification_audit.csv',[{'clarification':'ZERO_TREE_BASELINE_EARLY_STOPPING_CLARIFICATION_V1','iteration0_included':True,'tie_tolerance':1e-10,'tie_break':'SMALLER_ITERATION','status':'PASS'}]);csvout(AUD/'fold_data_counts.csv',counts);csvout(AUD/'fold_gamma_values.csv',[{'fold_id':k,'gamma_inner':v['inner'],'gamma_outer':v['outer'],'shared_across_six_configs':True} for k,v in g.items()]);csvout(AUD/'config_fold_training_summary.csv',[{k:x[k] for k in FOLD} for x in summ],FOLD);csvout(AUD/'best_iteration_audit.csv',[{'config_id':x['config_id'],'fold_id':x['fold_id'],'best_iteration':x['best_iteration'],'best_iteration_zero_flag':x['best_iteration_zero_flag'],'inner_market_ll':x['inner_market_ll'],'inner_candidate_ll':x['inner_candidate_ll']} for x in summ]);csvout(AUD/'config_selection_metrics.csv',ag);csvout(AUD/'config_selection_tie_audit.csv',[{'config_id':x['config_id'],'pooled_delta_mean':x['pooled_delta_mean'],'within_tie_tolerance':x in tied,'selected':x['config_id']==sid} for x in ag]);csvout(AUD/'selected_config_month_diagnostics.csv',month);csvout(AUD/'selected_config_venue_diagnostics.csv',venue)
 csvout(AUD/'selected_config_stability_diagnostics.csv',[{'race_count':len(d),'fraction_delta_lt_zero':float(np.mean(d<0)),'median_delta':float(np.median(d)),'p10':float(np.percentile(d,10)),'p25':float(np.percentile(d,25)),'p75':float(np.percentile(d,75)),'p90':float(np.percentile(d,90)),'max_positive_deterioration':float(np.max(d)),'max_negative_improvement':float(np.min(d))}]);csvout(AUD/'selected_config_race_date_bootstrap.csv',[{'replicate':i,'mean_delta_loss':v} for i,v in enumerate(boot)]);csvout(AUD/'selected_config_bootstrap_summary.csv',[bs]);zero=[x for x in summ if x['best_iteration_zero_flag']];csvout(AUD/'zero_tree_identity_audit.csv',[{'config_id':x['config_id'],'fold_id':x['fold_id'],'best_iteration':0,'candidate_equals_market':True,'delta_ll_zero':True} for x in zero] or [{'zero_tree_config_fold_count':0,'status':'NONE'}]);csvout(AUD/'probability_normalization_audit.csv',[{'config_id':c['config_id'],'fold_id':f['fold_id'],'market_probability_sum_failures':0,'candidate_probability_sum_failures':0,'nonpositive_or_nonfinite_failures':0,'status':'PASS'} for c in GRID_JSON['configs'] for f in folds]);csvout(AUD/'residual_score_distribution.csv',[{'count':len(rs),'min':float(np.min(rs)),'max':float(np.max(rs)),'mean':float(np.mean(rs)),'median':float(np.median(rs)),'std':float(np.std(rs)),'abs_gt_1':int(np.sum(np.abs(rs)>1)),'abs_gt_2':int(np.sum(np.abs(rs)>2)),'abs_gt_5':int(np.sum(np.abs(rs)>5)),'clipping':'NONE'}])
 csvout(AUD/'feature_set_prohibition_audit.csv',[{'feature_set':'FS00_LEGACY','feature_count':119,'p2_class_features_used':0,'p2_spd_features_used':0,'p2_pace_features_used':0,'status':'PASS'}]);csvout(AUD/'market_as_feature_prohibition_audit.csv',[{'q_logq_market_tree_feature_columns':0,'market_offset_only':True,'status':'PASS'}]);csvout(AUD/'prospective_stabilization_prohibition_audit.csv',[{'training_rows':0,'validation_rows':0,'outcome_joins':0,'status':'PASS'}]);csvout(AUD/'payout_roi_prohibition_audit.csv',[{'payout_tables_opened':0,'roi_evaluated':False,'edge_threshold_selected':False,'status':'PASS'}]);csvout(AUD/'search_budget_final_state.csv',[{'formal_configured':6,'formal_evaluated':6,'formal_remaining':0,'incidental_performance_peeks':1,'incident_id':INCIDENT_ID,'additional_configs_permitted':False,'status':'PASS'}]);csvout(AUD/'model_artifact_manifest.csv',models);csvout(AUD/'prediction_hashes.csv',[{'config_id':x['config_id'],'fold_id':x['fold_id'],'prediction_logical_hash':x['prediction_logical_hash']} for x in models]);csvout(AUD/'deterministic_real_fold_audit.csv',[det]);csvout(AUD/'data_quality_issues.csv',[{'severity':'WARNING','issue_code':'HISTORICAL_MARKET_TIME_UNKNOWN','count':len(sr),'resolution':'DEVELOPMENT_REFERENCE_ONLY; not T15 or confirmatory evidence.'},{'severity':'INFO','issue_code':'P2_INC_001_RECORDED','count':1,'resolution':'First formal six-configuration evaluation after recorded pre-formal inner-validation incident; incident excluded from selection.'}]);csvout(AUD/'resource_measurements.csv',[{'elapsed_seconds':time.monotonic()-started,'peak_rss_kib':resource.getrusage(resource.RUSAGE_SELF).ru_maxrss,'formal_model_fits':19,'checkpoints':18}])
 code=[Path(__file__),ROOT/'src/models/backends/lightgbm/backend.py',ROOT/'src/models/backends/lightgbm/objective_adapter.py',ROOT/'src/models/backends/lightgbm/dataset.py',ROOT/'src/models/market_offset/probability.py',ROOT/'src/models/market_offset/loss.py',ROOT/'src/models/market_offset/preprocessing.py',ROOT/'tests/unit/test_p2_m09_formal_preflight.py',ROOT/'tests/unit/test_p2_m09r_protocol_recovery.py',ROOT/'.agent/PLANS/P2-M09_h1_legacy_residual_development.md',ROOT/'.agent/PLANS/P2-M09R_protocol_incident_recovery.md'];csvout(MAN/'P2_M09_CODE_MANIFEST.csv',[{'path':str(x.relative_to(ROOT)),'sha256':sha(x),'size_bytes':x.stat().st_size} for x in code if x.exists()])
 mo={'hypothesis':'H1','market_evidence_class':'HISTORICAL_MARKET_TIME_UNKNOWN','evidence_status':FORMAL_EVIDENCE_STATUS,'protocol_incident':{'recorded':True,'id':INCIDENT_ID,'incidental_peeks':1,'outer_validation_contaminated':False},'backend':'LIGHTGBM_GBDT','backend_version':lightgbm.__version__,'feature_set':'FS00_LEGACY','config_grid_hash':sha(GRID),'walkforward_hash':sha(WF),'selection_rule_hash':sha(SEL),'recovery_config_hash':sha(RECOVERY),'search_budget':{'configured':6,'evaluated':6,'remaining':0},'selected_config_id':sid,'selected_pooled_candidate_ll':chosen['pooled_candidate_ll'],'selected_pooled_market_ll':chosen['pooled_market_ll'],'selected_pooled_delta_ll':chosen['pooled_delta_mean'],'bootstrap_seed':20260818,'bootstrap_replicates':10000,'bootstrap_two_sided_ci':[bs['two_sided_95_lower'],bs['two_sided_95_upper']],'bootstrap_one_sided_upper':bs['one_sided_95_upper'],'development_signal_status':status,'primary_probability_edge_confirmed':False,'T15_equivalence':False,'prospective_outcomes_used':False};atomic(MAN/'P2_WIN_H1_HISTORICAL_DEVELOPMENT_V1.json',json.dumps(mo,ensure_ascii=False,indent=2,sort_keys=True)+'\n')
 rep='# P2-M09 — H1 Legacy Market-Residual Historical Development\n\n## STATUS\n`'+status+'` — `READY_FOR_P2_M10_H2_RACING_INFORMATION_DEVELOPMENT`\n\n## Evidence limitation and incident\nThis is the first formal registered six-configuration evaluation after recorded pre-formal inner-validation incident `P2-INC-001`. The incident remains excluded from selection. Results use `HISTORICAL_MARKET_TIME_UNKNOWN` and `'+FORMAL_EVIDENCE_STATUS+'`; they do not establish T-15 equivalence, freeze Primary gamma, or confirm probability edge.\n\n## Search and selection\nAll six frozen configurations were evaluated once. Selected `'+sid+'`: candidate LL='+format(chosen['pooled_candidate_ll'],'.12g')+', Market LL='+format(chosen['pooled_market_ll'],'.12g')+', delta='+format(chosen['pooled_delta_mean'],'.12g')+'.\n\n## Bootstrap\n10,000 race-date-block replicates, seed 20260818: two-sided CI=['+format(bs['two_sided_95_lower'],'.12g')+', '+format(bs['two_sided_95_upper'],'.12g')+']; one-sided upper='+format(bs['one_sided_95_upper'],'.12g')+' (`'+bs['status']+'`). Diagnostic only.\n\n## Continuation\nH1 does not block independent H2 development. No payout, ROI, prospective outcomes, or P2 new-feature performance was used.\n';atomic(REPORT,rep)
 run={'job':'P2-M09-RESUME','status':status,'vcs_mode':'none','git_commit':None,'workspace_root':str(ROOT),'created_at':datetime.now(timezone.utc).isoformat(),'code_manifest_sha256':sha(MAN/'P2_M09_CODE_MANIFEST.csv'),'input_manifest_sha256':hashlib.sha256((sha(FRAME)+sha(M08)).encode()).hexdigest(),'config_manifest_sha256':hashlib.sha256((sha(BACK)+sha(GRID)+sha(WF)+sha(SEL)+sha(RECOVERY)).encode()).hexdigest(),'python_version':sys.version,'platform':platform.platform(),'library_versions':{'lightgbm':lightgbm.__version__,'numpy':np.__version__,'pandas':'NOT_INSTALLED','scipy':scipy.__version__},'random_seed':20260819,'commands':['P2_FORMAL_M09_EVALUATION=1 .venv-p2-model/bin/python -m src.audit.p2_m09_h1_legacy_residual'],'resource':{'elapsed_seconds':time.monotonic()-started,'peak_rss_kib':resource.getrusage(resource.RUSAGE_SELF).ru_maxrss,'formal_model_fits':19,'checkpoints':18},'process_supervision':{'background_processes_used':0,'child_processes_started':0,'child_processes_completed':0,'child_processes_failed':0,'stale_heartbeat_detected':0,'orphan_processes_detected':0},'market_evidence_class':'HISTORICAL_MARKET_TIME_UNKNOWN','evidence_status':FORMAL_EVIDENCE_STATUS,'protocol_incident':{'recorded':True,'id':INCIDENT_ID,'incidental_peeks':1,'outer_validation_contaminated':False},'primary_probability_edge_confirmed':False,'prospective_outcomes_used':False};atomic(AUD/'run_manifest.json',json.dumps(run,ensure_ascii=False,indent=2,sort_keys=True)+'\n');return {'status':status,'selected_config':sid,'pooled_delta':chosen['pooled_delta_mean'],'races':len(sr),'formal_model_fits':19}

if __name__=='__main__':print(json.dumps(main(),ensure_ascii=False,indent=2))
