"""Frozen constants for P2 WIN Market-offset race softmax."""

OBJECTIVE_VERSION = "CUSTOM_MARKET_OFFSET_RACE_SOFTMAX_V1"
HESSIAN_VERSION = "DIAGONAL_SOFTMAX_HESSIAN_APPROX_V1"
ZERO_RESIDUAL_TOLERANCE = 1e-12
GRADIENT_FINITE_DIFFERENCE_TOLERANCE = 1e-6
HESSIAN_FINITE_DIFFERENCE_TOLERANCE = 1e-5

